// Generated by cargo xtask bindings.
import type { FlowExecutionLimits } from './contract.js';
export const FLOW_DOCUMENT_VERSION = 2;
export const DEFAULT_FLOW_EXECUTION_LIMITS = {
  "pending_events": 4096,
  "retained_bytes": 67108864,
  "node_retained_bytes": 16777216,
  "provider_queue": {
    "items": 32,
    "bytes": 1048576,
    "max_event_bytes": 262144,
    "policy": "backpressure"
  }
} satisfies FlowExecutionLimits;
