use crate::Result;
use battersea_flow::{document::serialize_canonical_document, FlowDocument};
use serde_json::{json, Value};
use std::{fs, path::Path};

fn type_expression(schema: &Value) -> Result<String> {
    if schema == &Value::Bool(true) {
        return Ok("unknown".into());
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return Ok(reference
            .strip_prefix("#/$defs/")
            .ok_or("Only local schema references are supported")?
            .into());
    }
    if let Some(variants) = schema.get("oneOf").and_then(Value::as_array) {
        return Ok(variants
            .iter()
            .map(type_expression)
            .collect::<Result<Vec<_>>>()?
            .join(" | "));
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return Ok(values
            .iter()
            .map(Value::to_string)
            .collect::<Vec<_>>()
            .join(" | "));
    }
    if let Some(value) = schema.get("const") {
        return Ok(value.to_string());
    }
    Ok(match schema.get("type").and_then(Value::as_str) {
        Some("string") => "string".into(),
        Some("boolean") => "boolean".into(),
        Some("integer" | "number") => "number".into(),
        Some("null") => "null".into(),
        Some("array") => format!("Array<{}>", type_expression(&schema["items"])?),
        Some("object") => {
            let mut fields = Vec::new();
            if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
                for (name, value) in properties {
                    let required = schema
                        .get("required")
                        .and_then(Value::as_array)
                        .is_some_and(|items| items.iter().any(|item| item == name));
                    fields.push(format!(
                        "{}{}: {}",
                        serde_json::to_string(name)?,
                        if required { "" } else { "?" },
                        type_expression(value)?
                    ));
                }
            }
            if let Some(extra) = schema
                .get("additionalProperties")
                .filter(|value| **value != Value::Bool(false))
            {
                fields.push(format!("[key: string]: {}", type_expression(extra)?));
            }
            format!("{{ {} }}", fields.join("; "))
        }
        _ => return Err(format!("Unrepresentable TypeScript schema: {schema}").into()),
    })
}

fn write(root: &Path, file: &str, content: &str, check: bool) -> Result<()> {
    let path = root.join(file);
    if check {
        if fs::read_to_string(&path).ok().as_deref() != Some(content) {
            return Err(format!("{file} is stale; run cargo xtask bindings").into());
        }
    } else {
        fs::create_dir_all(path.parent().unwrap())?;
        fs::write(path, content)?;
    }
    Ok(())
}

pub fn generate(root: &Path, check: bool) -> Result<()> {
    let schema = battersea_flow::schema::contract_schema();
    let mut types =
        String::from("// Generated by cargo xtask bindings from battersea-flow's Rust contract.\n");
    for (name, schema) in schema["$defs"].as_object().ok_or("Missing definitions")? {
        types.push_str(&format!(
            "export type {name} = {};\n",
            type_expression(schema)?
        ));
    }
    write(
        root,
        "typescript/packages/flow/src/contract.ts",
        &types,
        check,
    )?;
    write(root, "typescript/packages/flow/src/defaults.ts", &format!(
        "// Generated by cargo xtask bindings.\nimport type {{ FlowExecutionLimits }} from './contract.js';\nexport const FLOW_DOCUMENT_VERSION = {};\nexport const DEFAULT_FLOW_EXECUTION_LIMITS = {} satisfies FlowExecutionLimits;\n",
        battersea_flow::document::FLOW_DOCUMENT_VERSION,
        serde_json::to_string_pretty(&battersea_flow::FlowExecutionLimits::default())?
    ), check)?;
    let schema = serde_json::to_string_pretty(&schema)? + "\n";
    for path in [
        "crates/battersea-flow/schemas/flow.schema.json",
        "typescript/packages/flow/schemas/flow.schema.json",
    ] {
        write(root, path, &schema, check)?;
    }
    let compatibility = fs::read_to_string(
        root.join("crates/battersea-flow/fixtures/token-type-compatibility.json"),
    )?;
    write(
        root,
        "typescript/packages/flow/fixtures/token-type-compatibility.json",
        &compatibility,
        check,
    )?;
    let flow: FlowDocument = serde_json::from_value(json!({
        "version": 2, "execution": battersea_flow::FlowExecutionPolicy { source_order: vec!["source".into()], limits: battersea_flow::FlowExecutionLimits::default() }, "flow_key": "example", "title": "Independent application", "whitespace_mode": "preserve",
        "nodes": [{"id": "source", "instance_name": "Source", "definition_name": "Echo", "parameter_values": {"label": "example"}}],
        "layout": {"editor.example": {"position": [12, 34], "viewport": {"zoom": 1.5}}},
        "metadata": {"application": {"tags": ["contract", "roundtrip"]}}
    }))?;
    let fixtures = format!("[\n{}\n]\n", serialize_canonical_document(&flow)?);
    for path in [
        "crates/battersea-flow/fixtures/flows.json",
        "typescript/packages/flow/fixtures/flows.json",
    ] {
        write(root, path, &fixtures, check)?;
    }
    write(root, "typescript/packages/flow/src/fixtures.ts", &format!("// Generated by cargo xtask bindings.\nimport type {{ FlowDocument }} from './contract.js';\nexport const flows = {} satisfies FlowDocument[];\n", fixtures.trim()), check)?;
    Ok(())
}
