[package]
name = "battersea-guard"
description = "Battersea guard contracts and implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
publish = false
include = ["src/**", "Cargo.toml", "LICENSE", "NOTICE"]

[dependencies]
anyhow.workspace = true
regex-lite.workspace = true
serde.workspace = true
serde_json.workspace = true
